## Programming Assignment 2: Lexical scoping

## This file contains two function definitions: makeCacheMatrix and cacheSolve
## * makeCacheMatrix builds an object containing a matrix and a variable 
##   that will cache its inverse.
## 
## * cacheSolve returns the inverse of the matrix contained within the object
##   passed as parameter. If the inverse has already been computed, it just
##   returns the previously stored inverse; otherwise it computes the inverse
##   and stores in the given object.


## The makeCacheMatrix function generates a special matrix object that can cache
## its inverse

makeCacheMatrix <- function(x = matrix()) {
  inverse <- NULL

  # This function changes the cached inverse
  setInverse <- function(newInverse) {
    inverse <<- newInverse
  }
  
  # This function retrieves the cached inverse
  getInverse <- function() {
    inverse
  }
  
  # This function changes the underlying matrix
  # (and hence invalidates its inverse until it is computed again)
  setMatrix <- function(newMatrix) {
    x <<- newMatrix
    inverse <<- NULL
  }
  
  # This function retrieves the underlying matrix
  getMatrix <- function() {
    x
  }
  

  list(getInverse = getInverse,
       setInverse = setInverse,
       setMatrix  = setMatrix,
       getMatrix  = getMatrix)
}


## The cacheSolve function receives a special matrix object generated by 
## makeCacheMatrix and returns the inverse of the underlying matrix.
## It the inverse has been computed before, it just access the cached value
## instead of recomputing the inverse.

cacheSolve <- function(x, ...) {
  inverse <- x$getInverse()

  if (is.null(inverse)) {
    # Data not cached. We have to compute the inverse
    inverse <- solve(x$getMatrix(), ...)
    x$setInverse(inverse)
  } 
  
  inverse
}
